language: ruby

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of HTMLProofer

addons:
    apt:
        packages:
            - libcurl4-openssl-dev # required to avoid SSL errors

install:
    # Download and install Hugo extended
    - curl -fSLO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
    - sudo dpkg -i hugo_extended_0.64.1_Linux-64bit.deb
    - bundle install

before_script:
    # Cleanup any generated content
    - rm -rf public/

script:
    # Generate a minified (production) version of the site
    - hugo --minify
    # Run HTMLProofer
    - bundle exec htmlproofer public/ --disable-external --url-ignore '/^mailto:\?body=/' --check-favicon --check-html --check-img-http --check-opengraph
