baseURL: https://yktoo-com.onrender.com/
languageCode: en-us
pygmentsCodeFences: true
pygmentsStyle: tango
title: Yktoo
theme: yktoo-bootstrap
summaryLength: 15
googleAnalytics: UA-19569086-3
enableRobotsTXT: true

# Language settings
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    en:
        weight: 1
        languageName: English
        params:
    ru:
        weight: 2
        languageName: Русский
        params:
            author: Дмитрий Канн
            copyright:
                from: 2000
                by: Дмитрий Канн
            date_format: Mon, 2 Jan 2006 # TODO localise
            short_date_format: 02.01.2006
    nl:
        weight: 3
        languageName: Nederlands
        params:

permalinks:
    # Arrange blog posts in /blog/post/YYYY/MM/DD-name structure
    blog: /blog/post/:year/:month/:day-:title/

taxonomies:
    tag: tags

menu:
    nav:
        # Items with weights below 100 go on the left
        - identifier: archive
          url: '/blog/archive'
          weight: 1
        - identifier: faq
          url: '/blog/faq'
          weight: 2
        - identifier: software
          url: '/software'
          weight: 3
        - identifier: radiolaria
          url: '/radiolaria'
          weight: 4
        - identifier: videos
          url: '/video'
          weight: 5

        # Items with weights >= 100 go on the right
        - identifier: about
          url: '/about/'
          pre: <i class="fas fa-info-circle"></i>
          weight: 100
        - identifier: contact
          url: '/about/contact/'
          pre: <i class="fas fa-envelope"></i>
          weight: 101

params:
    author: Dmitry Kann
    postsPerPage: 6
    copyright:
        from: 2000
        by: Dmitry Kann
