baseURL: https://yktoo-com.onrender.com/
languageCode: en-us
pygmentsCodeFences: true
pygmentsStyle: tango
title: Yktoo
summaryLength: 15
googleAnalytics: UA-19569086-3
enableRobotsTXT: true

# Language settings
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    en:
        weight: 1
        languageName: English
        params:
    ru:
        weight: 2
        languageName: Русский
        params:
            author: Дмитрий Канн
            date_format: Mon, 2 Jan 2006 # TODO localise
            short_date_format: 02.01.2006
    nl:
        weight: 3
        languageName: Nederlands
        params:

# Related indices settings
related:
    threshold: 50
    includeNewer: true
    toLower: false
    indices:
        - name: software
          weight: 1

permalinks:
    # Arrange blog posts in /blog/post/YYYY/MM/DD-name structure
    blog: /blog/post/:year/:month/:day-:title/
    # Nest tags and series under /blog/
    tags: /blog/tags/:title/
    series: /blog/series/:title/
    # Radiolaria music albums and tracks
    musicalbums: /radiolaria/:title/
    radiolaria: /radiolaria/tracks/:title/

taxonomies:
    tag: tags
    series: series
    musicalbum: musicalbums

menu:
    nav:
        # Items with weights below 100 go on the left
        - identifier: archive
          url: '/blog/archive/'
          weight: 1
        - identifier: faq
          url: '/blog/faq/'
          weight: 2
        - identifier: software
          url: '/software/'
          weight: 3
        - identifier: radiolaria
          url: '/radiolaria/'
          weight: 4
        - identifier: videos
          url: '/video/'
          weight: 5

        # Items with weights >= 100 go on the right
        - identifier: about
          url: '/about/'
          pre: <i class="fas fa-info-circle"></i>
          weight: 100
        - identifier: contact
          url: '/about/contact/'
          pre: <i class="fas fa-envelope"></i>
          weight: 101

    blog:
        - identifier: timeline
          url: '/blog/archive/'
          pre: <i class="fas fa-calendar-alt bycon"></i>
          weight: 1
        - identifier: map
          url: '/blog/map/'
          pre: <i class="fas fa-map-marker-alt bycon"></i>
          weight: 2
        - identifier: tags
          url: '/blog/tags/'
          pre: <i class="fas fa-tags bycon"></i>
          weight: 3
        - identifier: seriesPlural
          url: '/blog/series/'
          pre: <i class="fas fa-layer-group bycon"></i>
          weight: 4
        - identifier: blogSubscribe
          url: '/blog/subscribe/'
          pre: <i class="fas fa-rss bycon"></i>
          weight: 5

    footer:
        - identifier: archive
          url: '/blog/archive/'
          weight: 1
        - identifier: map
          url: '/blog/map/'
          weight: 2
        - identifier: tags
          url: '/blog/tags/'
          weight: 3
        - identifier: seriesPlural
          url: '/blog/series/'
          weight: 4
        - identifier: blogSubscribe
          url: '/blog/faq/'
          weight: 5
        - identifier: blogSubscribe
          url: '/blog/subscribe/'
          weight: 6
        - identifier: about
          url: '/about/'
          weight: 7
        - identifier: contact
          url: '/about/contact/'
          weight: 8
        - identifier: software
          url: '/software/'
          weight: 9
        - identifier: radiolaria
          url: '/radiolaria/'
          weight: 10
        - identifier: videos
          url: '/video/'
          weight: 11

params:
    author: Dmitry Kann
    postsPerPage: 6
    licenses:
        gpl3: 'http://www.gnu.org/licenses/gpl.html'
        lgpl21: 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html'
        lgpl3: 'https://www.gnu.org/licenses/lgpl-3.0.html'
        mpl11: 'http://mozilla.org/MPL/1.1/'
        mpl2: 'http://mozilla.org/MPL/2.0/'
    # TODO
    cookieConsentInfoUrl: /about
    copyrightUrl: /about
