# RU language redirects
[[redirects]]
    from = "/"
    to = "/ru/"
    force = true
    conditions = {Language = ["ru", "uk", "be"]}

[[redirects]]
    from = "/"
    to = "/ru/"
    force = true
    conditions = {Country = ["RU", "UA", "BY"]}

# NL language redirects
[[redirects]]
    from = "/"
    to = "/nl/"
    force = true
    conditions = {Language = ["nl"]}

[[redirects]]
    from = "/"
    to = "/nl/"
    force = true
    conditions = {Country = ["NL", "BE"]}

# Fallback language redirect
[[redirects]]
    from = "/"
    to = "/en/"
    force = true
